export const UI_LANGUAGE_STORAGE_KEY = 'surveycalc.uiLanguage';

export const UI_LANGUAGE_OPTIONS = [
  { code: 'en', label: 'EN' },
  { code: 'fr', label: 'FR' },
];

let currentUiLanguage = 'en';

const UI_COPY = {
  en: {
    header: {
      kicker: 'Professional Geomatics Platform',
      subtitle: 'Coordinate Conversion, CRS Detection, Benchmarking, and Survey Computation Workspace',
      language: 'Interface language',
    },
    footer: {
      copyright: 'Survey Calculator | MIT License',
      terms: 'Terms of Service',
      security: 'Security',
      github: 'GitHub (Profile)',
      openSource: 'Open Source',
      request: 'Request Code or Website (Email)',
      madeBy: 'Made by',
    },
    app: {
      currentSession: 'Current Session',
      interactiveMap: 'Interactive Map',
      newOperation: 'New Operation',
      newOperationTitle: 'New Operation',
      newOperationDescription: 'Resets the entire workspace for a fresh session. Clears all loaded points, CAD geometry, measurements, and panel states. Use this when starting a brand-new survey project.',
      clearMeasurementsTitle: 'Clear Measurements',
      clearMeasurementsDescription: 'Removes all currently placed measurement points from the map. Use this to start a fresh distance or area measurement from scratch.',
      clear: 'Clear',
      undoTitle: 'Undo Last Point (Ctrl+Z)',
      undoDescription: 'Removes the most recently placed measurement point. Step back through your clicks one at a time to correct mistakes without losing all measurements.',
      undo: 'Undo',
      redoTitle: 'Redo Point (Ctrl+Y)',
      redoDescription: 'Re-applies a previously undone measurement point. Use after Undo if you removed a point by mistake.',
      redo: 'Redo',
      closePolygonTitle: 'Close Polygon',
      closePolygonDescription: 'Connects the last measurement point back to the first to close the polygon. Once closed, the tool calculates total perimeter and enclosed area automatically.',
      close: 'Close',
      measureToolTitle: 'Measure Tool',
      measuringTitle: 'Measuring - Click to Stop',
      measureActiveDescription: 'Measurement mode is active. Click converted points on the map to drop pins. The tool computes distance, bearing, and cumulative length for each leg. Click again to deactivate.',
      measureInactiveDescription: 'Activates measurement mode. Once active, click any converted point on the map to start placing measurement pins. Distances, bearings, and running totals are calculated in real time.',
      measure: 'Measure',
      measuring: 'Measuring...',
      mapFocus: 'Map Focus',
      balancedView: 'Balanced View',
      balancedViewDescription: 'Restores the balanced split layout where the coordinate converter panel and the map share equal screen space.',
      mapFocusDescription: 'Expands the map to occupy most of the screen, hiding side panels for an unobstructed view of your survey data. Click again to restore the balanced layout.',
      projectLayers: 'Project Layers',
      showAll: 'Show all',
      hideAll: 'Hide all',
      measureResults: 'Measure Results',
      distance: 'Distance',
      angle: 'Angle',
      meters: 'meters',
      kilometers: 'kilometers',
      degree: 'degree (°)',
      measureHint: 'Click converted map points to add measure points (3+ for polygon area)',
      measureEmpty: 'Turn on Measure, then click two converted points on the map.',
      convertedPoint: 'Converted point',
      clickSecondPoint: 'Click a second converted point for P2',
      searchTooltipTitle: 'Point Search & Filter',
      searchTooltipDescription: 'Opens the search panel. Search points by label or coordinates, filter by attribute values, and isolate specific subsets for analysis. Active points are highlighted on the map.',
      geoidPreviewTitle: 'Geoid Grid Preview',
      geoidPreviewDescription: 'Visualize geoid grid coverage and accuracy. View the spatial extent of available geoid data, inspect height variations, and upload custom grids for your project area.',
      diagnosticsTooltipTitle: 'Performance Diagnostics',
      diagnosticsTooltipDescription: 'Opens the diagnostics panel. Displays rendering statistics, total point and entity counts, layer summaries, and memory usage. Helps identify bottlenecks when working with large datasets.',
      measurementsTooltipTitle: 'Multi-Point Measurements',
      measurementsTooltipDescription: 'Opens the measurements panel. Shows detailed surveying metrics for each measured leg: horizontal distance, geodesic distance, bearing, azimuth, and cumulative totals along the traverse.',
      elevationTooltipTitle: 'Elevation Profile',
      elevationTooltipDescription: 'Opens the elevation profile panel. Visualizes terrain height changes along a measured transect using external elevation data. Useful for slope analysis and cross-section studies.',
      batchTooltipTitle: 'Batch Operations',
      batchTooltipDescription: 'Opens the batch operations panel. Apply bulk coordinate transformations, CRS reprojections, or data edits to all loaded points simultaneously, saving time on large datasets.',
      markerTooltipTitle: 'Marker Style Manager',
      markerTooltipDescription: 'Opens the marker style panel. Customize how points are rendered on the map: change colors, icons, sizes, and cluster appearance per point type or layer.',
      conflictTooltipTitle: 'Smart Conflict Detection',
      conflictTooltipDescription: 'Opens the conflict detection panel. Automatically identifies duplicate points, overlapping geometries, and inconsistent coordinate systems across your loaded data, then highlights issues on the map.',
      dxfLayerTooltipTitle: 'DXF Layer Manager',
      dxfLayerTooltipDescription: 'Opens the layer manager. Toggle individual DXF layers on or off to control map visibility. Essential when working with complex multi-layer CAD drawings that have many overlapping entities.',
      hatchTooltipTitle: 'Hatch Area Calculator',
      hatchTooltipDescription: 'Opens the hatch area panel. Computes surface areas from DXF HATCH entities and reports results in square metres or hectares.',
      dxfDiffTooltipTitle: 'DXF Diff - Compare Files',
      dxfDiffTooltipDescription: 'Opens the DXF comparison panel. Load two DXF files side by side and highlight added, removed, and moved geometries.',
      entityBreakdownTooltipTitle: 'Entity Type Breakdown',
      entityBreakdownTooltipDescription: 'Opens the entity breakdown panel. Shows a statistical summary of CAD entity types found in the loaded DXF file, including counts per layer.',
      entityPickerTooltipTitle: 'CAD Entity Picker',
      entityPickerTooltipDescription: 'Opens the entity picker. Click directly on a CAD line or polyline rendered on the map to inspect its properties.',
      surfaceViewTitle2d: '2D Map',
      surfaceViewTitle3d: '3D Surface View',
      surfaceViewDescription: 'Switch between the 2D Leaflet map and a 3D surface viewer that renders 3DFACE / TIN triangles with elevation color-coding.',
      view2d: '2D View',
      view3d: '3D View',
      exportPlanTitle: 'Export Plan',
      closeExportTitle: 'Close Export Panel',
      exportPlanDescription: 'Opens the export panel. Configure your map for output as PDF or PNG: add a project title, surveyor, scale, notes, page size, and orientation before downloading.',
      closeExport: 'Close Export',
      exportPlan: 'Export Plan',
      projectName: 'Project Name',
      surveyor: 'Surveyor',
      scale: 'Scale',
      suggested: 'Suggested',
      apply: 'Apply',
      pdfPaper: 'PDF Paper',
      pdfOrientation: 'PDF Orientation',
      landscape: 'Landscape',
      portrait: 'Portrait',
      notes: 'Notes',
      projectPlaceholder: 'Survey Plan',
      surveyorPlaceholder: 'Name / team',
      scalePlaceholder: 'Example: 1:500',
      notesPlaceholder: 'Site notes, datum remarks, quality controls...',
      exportPng: 'Export PNG',
      exportPdf: 'Export PDF',
      mapNotReady: 'Map is not ready yet. Please try again in a second.',
      mapExportFailed: 'Map export failed: {{message}}',
    },
    converter: {
      quickActions: 'Quick Actions',
      goToBulk: 'Go to Bulk',
      goToExports: 'Go to Exports',
      resetBulk: 'Reset Bulk',
      singlePointConversion: 'Single Point Conversion',
      inputFormat: 'Input Format:',
      outputFormat: 'Output Format:',
      decimalDegrees: 'Decimal Degrees (DD)',
      degreesMinutesSeconds: 'Degrees/Minutes/Seconds (DMS)',
      bothDdAndDms: 'Both DD and DMS',
      inputFormatHintDms: 'Formats: 48°51\'24"N, 48:51:24, or 48 51 24',
      outputFormatHintDms: 'Shown with N/S/E/W (e.g., 48°51\'24"N)',
      outputFormatHintBoth: 'Shows separate columns for DD and DMS',
      xLon: 'X / Lon',
      yLat: 'Y / Lat',
      height: 'Height',
      geoidMode: 'Geoid mode:',
      geoidGrid: 'Geoid grid:',
      notAvailable: 'N/A',
      convertSinglePoint: 'Convert Single Point',
      detecting: 'Detecting...',
      detectCrs: 'Detect CRS',
      resetSingle: 'Reset Single',
      confidenceScale: 'Confidence Scale',
      confidenceHigh: '90-100%: High - Extents-based match',
      confidenceGood: '75-89%: Good - UTM/metadata match',
      confidenceFair: '60-74%: Fair - Trial transform',
      confidenceLow: 'Below 60%: Low - Use with caution',
      detectedCrsSuggestions: 'Detected CRS suggestions',
      topDetectionsOnly: 'Top detections only',
      allDetections: 'All detections',
      expandList: 'Expand List',
      compactList: 'Compact List',
      plotOnMap: 'Plot on Map',
      topModeShows: 'Top mode shows and plots the top {{count}} highest-confidence detections.',
      allModePlots: 'All mode plots all {{count}} detections.',
      lowConfidenceWarning: 'Low confidence detection. Review the top 3 suggestions and plot points on map before applying.',
      use: 'Use',
      showingSuggestions: 'Showing {{visible}} of {{total}} suggestions. Use Expand List for full ranking.',
      bulkConversionImport: 'Bulk Conversion / Import',
      hide: 'Hide',
      show: 'Show',
      bulkInputToggle: '{{action}} Bulk input (one point per line: [ID] x y [z])',
      uploading: 'Uploading',
      uploadBulkFile: 'Upload bulk file (CSV/TXT/GeoJSON/GPX/KML/KMZ/ZIP/XLSX)',
      chooseFile: 'Choose file',
      loadDwgSample: 'Load DWG Sample',
      convertFileBulk: 'Convert File/Bulk',
      detectCrsVisualizeOnlyTitle: 'Detect CRS + Visualize Only',
      detectCrsVisualizeOnlyDescription: 'Automatically detects the coordinate reference system of the loaded DXF or DWG file and renders its geometry directly on the map without applying any CRS conversion. Use this to inspect a CAD file\'s original position and verify its CRS before converting.',
      preparingPreview: 'Preparing Preview...',
      detectCrsVisualizeOnly: 'Detect CRS + Visualize Only',
      downloadCadSummaryTitle: 'Download CAD Summary Report',
      downloadCadSummaryDescription: 'Generates and downloads a human-readable text report of the CAD file inspection results. Includes layer names, entity counts, detected CRS, warnings, and repair actions applied during import.',
      downloadCadSummary: 'Download CAD Summary',
      downloadRawCadDebugTitle: 'Download Raw CAD Debug JSON',
      downloadRawCadDebugDescription: 'Downloads the full raw diagnostic JSON payload from the CAD parser. This is intended for technical support and debugging - it contains every internal field returned by the server including raw vertex data and error traces.',
      downloadRawCadDebug: 'Download Raw CAD Debug',
      cadInspectionValidation: 'CAD Inspection & Validation',
      selectCadFileHint: 'Select a DXF or DWG file, then use Detect CRS + Visualize Only (preview) or Convert File/Bulk to inspect routing, detected CRS, and parsed bounds.',
      benchmarkReferenceValidation: 'Benchmark / Reference Validation',
      geoidReadyBanner: '3D conversion ready. Geoid grids will load automatically when needed.',
      loadedGrids: 'Loaded grids: {{value}}',
      none: 'none',
      ready: 'ready',
      autoDetected: 'CRS Auto-Detected',
      detectedTop: 'We detected these top {{count}} coordinate systems. Click any option below to choose it:',
      whyRankedFirst: 'Why {{code}} is ranked first',
      whyNotSecond: 'Why not #2?',
      selected: 'SELECTED',
      match: '{{count}}% match',
      fromCrs: 'From CRS',
      toCrs: 'To CRS',
      swapCrsTitle: 'Swap From / To CRS',
      swapCrsDescription: 'Swaps the source (From) and target (To) coordinate reference systems. Useful when you need to reverse a conversion - for example switching from RGF93 -> WGS84 to WGS84 -> RGF93 in one click.',
      swapCrsAria: 'Swap From and To CRS',
      undoAction: 'Undo',
      redoAction: 'Redo',
      projectPresets: 'Project Presets',
      summary: {
        high: 'High confidence',
        good: 'Good confidence',
        moderate: 'Moderate confidence',
        low: 'Low confidence',
        primarySignal: 'Primary signal: {{reason}}',
        rankingStrength: 'Ranking strength: {{label}} ({{percent}}%).',
        gapClear: 'Top-vs-next gap: {{points}} points. This is a clear winner.',
        gapReview: 'Top-vs-next gap: {{points}} points. Selection is reasonable but still worth a quick review.',
        gapManual: 'Top-vs-next gap: {{points}} points. The top candidates are close, so manual confirmation is recommended.',
        geographicPenalty: 'Domain filter applied: projected candidates were down-ranked because the input behaves like geographic lon/lat degrees.',
        projectedPenalty: 'Domain filter applied: geographic candidates were down-ranked because the input behaves like projected metric coordinates.',
        comparison: '{{top}} was kept above {{second}} by a {{points}}-point margin. #2 signal: {{reason}}',
      },
    },
    panels: {
      searchTitle: 'Point Search & Filter',
      searchPlaceholder: 'Search by name, ID...',
      crs: 'CRS',
      allCrs: 'All CRS',
      sourceType: 'Source Type',
      allTypes: 'All Types',
      hideAdvanced: 'Hide Advanced',
      showAdvanced: 'Show Advanced',
      elevationMin: 'Elevation Min (m)',
      elevationMax: 'Elevation Max (m)',
      min: 'Min',
      max: 'Max',
      matchingPoints: 'Matching: {{count}} / {{total}} points',
      applyFilter: 'Apply Filter',
      clear: 'Clear',
      multiMeasurementsTitle: 'Multi-Point Measurements',
      live: 'Live',
      pointsShort: 'pts',
      distance: 'Distance',
      avgElevation: 'Avg elev',
      gain: 'Gain',
      loss: 'Loss',
      minElevation: 'Min elev',
      maxElevation: 'Max elev',
      area: 'Area',
      perimeter: 'Perimeter',
      closePolygon: 'Close polygon',
      exportProfile: 'Export profile',
      measurementNamePlaceholder: 'Name this measurement...',
      save: 'Save',
      saved: 'Saved',
      listView: 'List view',
      compareTable: 'Compare table',
      exportSavedCsv: 'Export saved CSV',
      enableMeasure: 'Enable measure mode and click 2+ map points to start measuring',
      batchOperationsTitle: 'Batch Operations',
      pointsSelectedFromTotal: '{{count}} points selected from {{total}} total',
      pointsTotal: '{{total}} points total',
      operation: 'Operation',
      selectOperation: 'Select Operation',
      viewStatistics: 'View Statistics',
      exportCsv: 'Export as CSV',
      addElevationOffset: 'Add Elevation Offset',
      deleteSelected: 'Delete Selected',
      elevationOffset: 'Elevation Offset (m)',
      elevationOffsetExample: 'e.g., 2.5 or -1.5',
      addOffsetToPoints: 'Will add {{offset}} m to all {{count}} point elevation values',
      deleteWarning: 'This will permanently delete {{count}} point(s). This cannot be undone.',
      confirmDelete: 'Confirm Delete',
      yesDelete: 'Yes, Delete',
      cancel: 'Cancel',
      exportPoints: 'Export {{count}} Points',
      applyOffset: 'Apply Offset to {{count}} Points',
      selectOperationAbove: 'Select an operation above',
      invalidElevationOffset: 'Invalid elevation offset',
      batchStatsTitle: 'Batch Statistics',
      elevations: 'Elevations',
      avg: 'Avg',
      crsDistribution: 'CRS Distribution',
      sourceTypes: 'Source Types',
      diagnosticsTitle: 'Performance Diagnostics',
      healthLarge: 'LARGE',
      healthModerate: 'MODERATE',
      healthGood: 'GOOD',
      data: 'Data',
      performance: 'Performance',
      points: 'Points',
      lines: 'Lines',
      polylines: 'Polylines',
      arcs: 'Arcs',
      circles: 'Circles',
      ellipses: 'Ellipses',
      splines: 'Splines',
      bulgeArcs: 'Bulge arcs',
      proxyCurves: 'Proxy curves',
      approxCurves: 'Approx curves',
      vertices: 'Vertices',
      memory: 'Memory',
      render: 'Render',
      fps: 'FPS',
      optimizationTips: 'Optimization Tips',
      tipsLargePointCount: 'Large point count: Enable Duplicate Remover or Filter points',
      tipsManyVertices: 'Many vertices: CAD geometry is complex; zoom out for faster rendering',
      tipsHighMemory: 'High memory usage: Consider splitting into smaller files',
      tipsLowFps: 'Low FPS: Try disabling labels or zooming to specific area',
      dxfLayersTitle: 'DXF Layers',
      noDxfLayerData: 'No DXF layer data available. Import a DXF or DWG file to see its layer tree.',
      visibleFraction: '{{visible}} / {{total}} visible',
      declared: 'Declared',
      standardized: 'Standardized',
      renamed: 'Renamed',
      showAllLayers: 'Show All Layers',
      showAllLayersDescription: 'Makes all DXF layers visible on the map simultaneously. Use this to restore full visibility after selectively hiding individual layers.',
      hideAllLayers: 'Hide All Layers',
      hideAllLayersDescription: 'Hides every DXF layer from the map at once. Useful as a starting point when you want to selectively reveal only specific layers from a complex multi-layer drawing.',
      showAll: 'Show All',
      hideAll: 'Hide All',
      totalEntities: 'Total entities',
      textEntities: 'Text entities',
      toggleLayerTitle: 'Toggle layer: {{name}}\nOriginal names: {{originalNames}}',
      elevationProfileTitle: 'Elevation Profile',
      addMeasurementPoints: 'Add 2+ measurement points to generate profile',
      coverage: 'Coverage',
      measuredPointHeights: 'Measured point heights',
      onlineProfileUnavailable: 'Unable to fetch the online elevation profile.',
      terrainProfile: 'IGN GeoPlateforme terrain profile',
      fallbackHeights: 'Fallback: selected point heights only',
      sampledElevations: '{{count}} sampled elevations',
      selectedPoints: '{{count}} selected points',
      loadingTerrain: 'Loading terrain samples...',
      elevation: 'Elevation',
      total: 'Total',
      samples: 'Samples',
      selected: 'Selected',
      terrainChange: 'Terrain Change',
      slope: 'Slope',
      markerStylesTitle: 'Marker Styles & Legend',
      colorTab: 'Color',
      iconsTab: 'Icons',
      legendTab: 'Legend',
      colorByElevation: 'Color points by elevation rules',
      pointSizeScale: 'Point size scale',
      elevationRanges: 'Elevation ranges (m)',
      pickColor: 'Pick color',
      label: 'Label',
      newRange: 'New range',
      addRange: 'Add range',
      uploadIconsHelp: 'Upload PNG/SVG icons to replace default circle markers per point type.',
      upload: 'Upload',
      iconsRenderSize: 'Icons render at 24x24 px on the map.',
      showLegendOverlay: 'Show legend overlay on map',
      legendPreview: 'Legend Preview',
      customIcons: 'Custom Icons',
      elevationColors: 'Elevation Colors',
      legendEmpty: 'Enable elevation color rules or upload icons to populate the legend.',
      smartConflictTitle: 'Smart Conflict Detection',
      issueTypes: '{{count}} issue type(s)',
      noConflicts: 'No conflicts',
      pointsChecked: 'Points checked',
      axisAlerts: 'Axis alerts',
      duplicatePointIds: 'Duplicate point IDs',
      duplicatePointIdsDetail: '{{count}} duplicated exact ID value(s).',
      duplicateLogicalIds: 'Duplicate logical IDs across files',
      duplicateLogicalIdsDetail: '{{count}} repeated base ID value(s) after source prefix stripping.',
      overlapElevations: 'Overlapping points with different elevations',
      overlapElevationsDetail: '{{count}} coordinate overlap group(s) show elevation mismatch >= 0.5 m.',
      inconsistentHeightUnits: 'Potential inconsistent height units',
      inconsistentHeightUnitsDetail: '{{count}} overlap group(s) contain height pairs close to meter/feet ratio.',
      inconsistentHeightUnitsMax: 'Very large absolute height values detected (max |Z| {{value}}).',
      mixedAxisOrder: 'Possible mixed axis order',
      mixedAxisOrderImpossible: '{{count}} point(s) exceed valid lat/lng bounds.',
      mixedAxisOrderSwap: '{{count}} coordinate pair(s) appear in swapped order (lat/lng and lng/lat).',
      topDuplicateIds: 'Top duplicate IDs',
      largestOverlapDelta: 'Largest overlap elevation delta',
      noMajorConflicts: 'No major ID, overlap, unit, or axis-order conflicts were detected in current visible points.',
      hatchAreasTitle: 'Hatch Areas',
      noHatches: 'No HATCH entities found. Import a DXF file with hatched regions to compute boundary areas.',
      regionsCount: '{{count}} region{{suffix}}',
      totalEnclosedArea: 'Total enclosed area',
      layer: 'Layer',
      solid: 'SOLID',
      dxfDiffTitle: 'DXF Diff',
      compareComplete: 'Compare complete',
      baselineOriginal: 'Baseline (A - original)',
      revisedCurrent: 'Revised (B - current)',
      loadingDxf: 'Loading DXF...',
      failedToLoadFile: 'Failed to load {{name}}: {{message}}',
      changesDetected: 'Changes detected (coord tolerance: {{tolerance}} m):',
      added: '{{count}} added',
      removed: '{{count}} removed',
      unchanged: '{{count}} unchanged',
      identicalFiles: 'Files are geometrically identical (within tolerance)',
      changesVerdict: '{{lineChanges}} line/polyline change(s) and {{pointChanges}} point change(s) detected',
      entityBreakdownTitle: 'Entity Breakdown',
      importCadForEntityStats: 'Import a DXF or DWG file to see entity type statistics.',
      entitiesCount: '{{count}} entities',
      noEntitiesFound: 'No entities found in loaded file.',
      moreLayers: '+ more layers...',
      entityPickerTitle: 'Entity Picker',
      active: 'Active',
      clickEntityToInspect: 'Click any CAD line or polyline on the map to inspect its properties.',
      type: 'Type',
      color: 'Color',
      source: 'Source',
      length: 'Length',
      mapUnits: 'map units',
      verticesLabel: 'Vertices',
      handle: 'Handle',
    },
    common: {
      yes: 'Yes',
      no: 'No',
      none: 'None',
      unknown: 'Unknown',
      file: 'File',
      type: 'Type',
      generated: 'Generated',
    },
    errors: {
      unexpectedRender: 'Unexpected rendering error.',
      failedToRender: '{{label}} failed to render',
      retry: 'Retry',
      copied: 'Copied',
      copyError: 'Copy error',
      backendUnavailable: 'Native DWG import requires the CAD backend service. Current CAD API target: {{target}}. Use the hosted CAD API or start "npm run dev:server" for local development.',
      invalidChunkPlan: 'Failed to build a valid CAD chunk upload plan.',
      chunkUploadFailed: 'Chunk {{index}}/{{total}} upload failed.',
      chunkFinalizeFailed: 'CAD chunk upload finalization failed.',
      fileTooLargeCad: 'File "{{name}}" is {{size}} MB, which exceeds the {{limit}} MB upload limit. Please reduce the file size or split it into smaller drawings.',
      uploadProgressUploading: 'Uploading {{size}} MB to CAD backend...',
      uploadProgressWaiting: 'Waiting for DWG-to-DXF conversion to start...',
      uploadProgressConverting: 'Converting DWG file - this can take 20-60 s for large drawings...',
      uploadProgressStillConverting: 'Still converting - complex drawings may take up to 2 minutes...',
      uploadProgressAlmostDone: 'Almost there - parsing the converted geometry...',
      uploadProgressChunked: 'Large CAD detected ({{size}} MB). Switching to chunked upload mode ({{mode}}).',
      uploadProgressFallback: 'Chunked upload unavailable on current backend. Falling back to direct upload...',
      uploadProgressComplete: 'Upload complete. Finalizing and parsing CAD geometry...',
      uploadProgressRefining: 'Quick CAD preview ready. Refining full-fidelity geometry...',
      uploadTimeout: 'The CAD backend did not respond within {{seconds}} seconds. This can happen with very complex DWG files. Retry the import or enable points-only preview manually if needed.',
      invalidCadResponse: 'CAD backend returned an invalid response.',
      cadHealthFailed: 'CAD backend health check failed for {{target}}.',
      fileTooLargeGeneric: 'File "{{name}}" is too large ({{size}}). The maximum supported size for {{type}} files is {{limit}}. Please reduce the file size or split it into smaller parts.',
      invalidKmlXml: 'Invalid KML XML in {{source}}',
      kmzMissingKml: 'KMZ archive does not contain a KML document.',
      unsupportedDwg: 'Unsupported DWG content. Native DWG requires the CAD backend service, or you can export the drawing as DXF and retry.',
      elevationNeedsTwoPoints: 'At least two measurement points are required to request an elevation profile.',
      ignRequestFailed: 'IGN elevation profile request failed ({{status}}).',
      ignNotEnoughSamples: 'IGN did not return enough elevation samples for this profile.',
      ignProfileBuildFailed: 'Unable to build profile data from IGN elevation samples.',
      elevationNeedsTwoPointsShort: 'At least two measurement points are required.',
      unknownOpenTopoProvider: 'Unknown OpenTopoData provider: {{providerId}}',
      openTopoProxyFailed: 'OpenTopoData proxy request failed ({{status}}).',
      openTopoRequestFailed: 'OpenTopoData request failed ({{status}}).',
      openTopoUnavailable: 'Unable to fetch OpenTopoData elevation profile. Check backend elevation API routing/CORS configuration.',
      openTopoNotEnoughSamples: 'OpenTopoData did not return enough elevation samples for this profile.',
      openTopoProfileBuildFailed: 'Unable to build profile data from OpenTopoData samples.',
      notEnoughValidMeasurementPoints: 'Not enough valid measurement points.',
      unknownElevationProvider: 'Unknown elevation provider: {{providerId}}',
      geoidFetchIndexFailed: 'Failed to fetch geoid index ({{status}})',
      geoidHttpFailed: 'HTTP {{status}}: {{statusText}}',
      geoidEmptyResponse: 'Empty response (content-length: {{length}})',
      geoidLoadFailed: 'Failed to load {{name}} from {{url}}: {{message}}',
      geoidNoUrl: 'No URL found for geoid grid {{name}}',
      geoidGridNotLoaded: 'Grid {{name}} not loaded',
      geoidRasterReadFailed: 'Failed to read raster window for {{name}} at ({{lon}}, {{lat}})',
      geoidGlobalFallbackFailed: 'Failed to load any global geoid grid. Make sure geoid files are accessible.',
    },
    reports: {
      metadataGeneratedAt: 'Generated At',
      metadataFromCrs: 'Source CRS',
      metadataToCrs: 'Target CRS',
      metadataGeoidMode: 'Geoid Mode',
      metadataGeoidName: 'Geoid Grid',
      metadataAccuracy: 'Estimated Accuracy (cm)',
      metadataConfidence: 'Confidence',
      metadataTotalRows: 'Total Rows',
      metadataSuccessRows: 'Success Rows',
      metadataErrorRows: 'Error Rows',
      confidenceLocal: 'Local/Unreferenced',
      confidenceNeedsReview: 'Needs Review',
      confidenceHigh: 'High Confidence',
      confidenceMedium: 'Medium Confidence',
      confidenceLow: 'Low Confidence',
      cadSummaryTitle: 'CAD Summary Report',
      cadSummarySubtitle: 'User-readable import diagnostics for DWG/DXF review.',
      overview: 'Overview',
      warnings: 'Warnings',
      unresolvedXrefs: 'Unresolved XREFs',
      missingBlocks: 'Missing Blocks',
      cyclicBlocks: 'Cyclic Blocks',
      recommendations: 'Recommendations',
      technicalDetail: 'Technical Detail',
      importNotice: 'Import Notice',
      processingMode: 'Processing Mode',
      processingRoute: 'Processing Route',
      rowsExtracted: 'Rows Extracted',
      detectedCrs: 'Detected CRS',
      backendMode: 'Backend Mode',
      usedConverter: 'Used Converter',
      axisNormalization: 'Axis Normalization',
      axisNormalized: 'Auto-corrected swapped source axes',
      noWarnings: 'No warnings were generated for this CAD import.',
      noMajorWarnings: 'No major CAD import warnings were detected in this run.',
      integrityVerified: 'Integrity Verified',
      serverPreScanRisk: 'Server Pre-scan Risk',
      serverRecommendedEngine: 'Server Recommended Engine',
      crsConfidence: 'CRS Confidence',
      preflightConfidence: 'Preflight Confidence',
      generated: 'Generated',
      referenceConfidence: 'Reference confidence',
      expandedInserts: 'Expanded inserts',
      flattenedEntities: 'Flattened entities',
      nestedBlockDepth: 'Nested block depth',
      technicalDetailHint: 'For engineering support, use the separate raw JSON debug export.',
    },
    providers: {
      ignLabel: 'IGN GeoPlateforme',
      ignDescription: 'France - RGE ALTI / BD ALTI, 1-25 m resolution',
      ignCoverage: 'France (best accuracy)',
      srtmLabel: 'OpenTopoData - SRTM 30 m',
      srtmDescription: 'Global (~60N-60S), USGS SRTM, ~30 m resolution',
      srtmCoverage: 'Global (lat -60 to +60)',
      asterLabel: 'OpenTopoData - ASTER 30 m',
      asterDescription: 'Global, NASA ASTER, ~30 m resolution',
      asterCoverage: 'Global',
      eudemLabel: 'OpenTopoData - EU-DEM 25 m',
      eudemDescription: 'Europe, EEA EU-DEM, ~25 m resolution',
      eudemCoverage: 'Europe',
      measuredLabel: 'Measured heights only',
      measuredDescription: 'Use the ellipsoidal/orthometric heights of the selected points (no DEM)',
      measuredCoverage: 'Any - offline',
      measuredSourceLabel: 'Measured point heights',
      ignSourceLabel: 'IGN GeoPlateforme profile',
      sampleLabel: 'Sample {{index}}',
      pointLabel: 'Point {{index}}',
      openTopoSourceLabel: 'OpenTopoData - {{dataset}}',
    },
  },
  fr: {
    header: {
      kicker: 'Plateforme professionnelle de géomatique',
      subtitle: 'Conversion de coordonnées, détection de SCR, benchmarking et espace de calcul topographique',
      language: 'Langue de l\'interface',
    },
    footer: {
      copyright: 'Survey Calculator | Licence MIT',
      terms: 'Conditions d\'utilisation',
      security: 'Sécurité',
      github: 'GitHub (Profil)',
      openSource: 'Open source',
      request: 'Demander le code ou un site web (e-mail)',
      madeBy: 'Réalisé par',
    },
    app: {
      currentSession: 'Session en cours',
      interactiveMap: 'Carte interactive',
      newOperation: 'Nouvelle opération',
      newOperationTitle: 'Nouvelle opération',
      newOperationDescription: 'Réinitialise tout l\'espace de travail pour une nouvelle session. Efface les points chargés, la géométrie CAO, les mesures et l\'état des panneaux.',
      clearMeasurementsTitle: 'Effacer les mesures',
      clearMeasurementsDescription: 'Supprime tous les points de mesure actuellement placés sur la carte pour recommencer une mesure.',
      clear: 'Effacer',
      undoTitle: 'Annuler le dernier point (Ctrl+Z)',
      undoDescription: 'Supprime le point de mesure placé le plus récemment, sans perdre l\'ensemble du tracé.',
      undo: 'Annuler',
      redoTitle: 'Rétablir le point (Ctrl+Y)',
      redoDescription: 'Rétablit un point de mesure précédemment annulé.',
      redo: 'Rétablir',
      closePolygonTitle: 'Fermer le polygone',
      closePolygonDescription: 'Relie le dernier point de mesure au premier pour fermer le polygone et calculer automatiquement le périmètre et l\'aire.',
      close: 'Fermer',
      measureToolTitle: 'Outil de mesure',
      measuringTitle: 'Mesure en cours - cliquer pour arrêter',
      measureActiveDescription: 'Le mode mesure est actif. Cliquez sur les points convertis de la carte pour poser des repères. L\'outil calcule distance, gisement et cumul pour chaque segment.',
      measureInactiveDescription: 'Active le mode mesure. Une fois actif, cliquez sur un point converti de la carte pour commencer à placer des repères.',
      measure: 'Mesurer',
      measuring: 'Mesure...',
      mapFocus: 'Focus carte',
      balancedView: 'Vue équilibrée',
      balancedViewDescription: 'Restaure la mise en page équilibrée où le convertisseur et la carte partagent l\'écran.',
      mapFocusDescription: 'Agrandit la carte pour occuper l\'essentiel de l\'écran et masquer les panneaux latéraux.',
      projectLayers: 'Couches du projet',
      showAll: 'Tout afficher',
      hideAll: 'Tout masquer',
      measureResults: 'Résultats de mesure',
      distance: 'Distance',
      angle: 'Angle',
      meters: 'mètres',
      kilometers: 'kilomètres',
      degree: 'degré (°)',
      measureHint: 'Cliquer sur les points convertis de la carte pour ajouter des points de mesure (3+ pour une aire)',
      measureEmpty: 'Activez Mesurer, puis cliquez sur deux points convertis de la carte.',
      convertedPoint: 'Point converti',
      clickSecondPoint: 'Cliquez sur un deuxième point converti pour P2',
      searchTooltipTitle: 'Recherche et filtre des points',
      searchTooltipDescription: 'Ouvre le panneau de recherche. Recherchez des points par libellé ou coordonnées, filtrez par attributs et isolez des sous-ensembles pour l\'analyse.',
      geoidPreviewTitle: 'Aperçu des grilles de géoïde',
      geoidPreviewDescription: 'Visualisez la couverture et la précision des grilles de géoïde. Consultez leur emprise spatiale et importez des grilles personnalisées.',
      diagnosticsTooltipTitle: 'Diagnostic de performance',
      diagnosticsTooltipDescription: 'Ouvre le panneau de diagnostic. Affiche les statistiques de rendu, les volumes d\'entités et l\'usage mémoire.',
      measurementsTooltipTitle: 'Mesures multipoints',
      measurementsTooltipDescription: 'Ouvre le panneau de mesures. Affiche les métriques topographiques détaillées pour chaque segment mesuré.',
      elevationTooltipTitle: 'Profil altimétrique',
      elevationTooltipDescription: 'Ouvre le panneau de profil altimétrique. Visualise les variations de terrain le long d\'un transect mesuré.',
      batchTooltipTitle: 'Opérations par lot',
      batchTooltipDescription: 'Ouvre le panneau des opérations par lot. Appliquez des transformations de coordonnées ou des modifications à tous les points chargés.',
      markerTooltipTitle: 'Gestionnaire de style des marqueurs',
      markerTooltipDescription: 'Ouvre le panneau de style des marqueurs. Personnalisez couleurs, icônes, tailles et apparence des clusters.',
      conflictTooltipTitle: 'Détection intelligente des conflits',
      conflictTooltipDescription: 'Ouvre le panneau de détection des conflits. Identifie automatiquement les doublons, recouvrements et incohérences de SCR.',
      dxfLayerTooltipTitle: 'Gestionnaire des couches DXF',
      dxfLayerTooltipDescription: 'Ouvre le gestionnaire de couches. Activez ou masquez les couches DXF pour contrôler la visibilité sur la carte.',
      hatchTooltipTitle: 'Calculateur d\'aires de hachures',
      hatchTooltipDescription: 'Ouvre le panneau d\'aires de hachures. Calcule les surfaces des entités HATCH en m² ou hectares.',
      dxfDiffTooltipTitle: 'Diff DXF - Comparer des fichiers',
      dxfDiffTooltipDescription: 'Ouvre le panneau de comparaison DXF. Chargez deux fichiers côte à côte et visualisez les géométries ajoutées, supprimées ou déplacées.',
      entityBreakdownTooltipTitle: 'Répartition des types d\'entités',
      entityBreakdownTooltipDescription: 'Ouvre le panneau de répartition des entités. Affiche un résumé statistique des types d\'entités CAD et des comptes par couche.',
      entityPickerTooltipTitle: 'Sélecteur d\'entités CAD',
      entityPickerTooltipDescription: 'Ouvre le sélecteur d\'entités. Cliquez directement sur une ligne ou polyligne CAD sur la carte pour inspecter ses propriétés.',
      surfaceViewTitle2d: 'Carte 2D',
      surfaceViewTitle3d: 'Vue surface 3D',
      surfaceViewDescription: 'Basculez entre la carte Leaflet 2D et la vue 3D des triangles 3DFACE / TIN avec codage couleur altimétrique.',
      view2d: 'Vue 2D',
      view3d: 'Vue 3D',
      exportPlanTitle: 'Exporter le plan',
      closeExportTitle: 'Fermer le panneau d\'export',
      exportPlanDescription: 'Ouvre le panneau d\'export. Configurez la sortie PDF ou PNG de la carte avec titre, géomètre, échelle, notes, format de page et orientation.',
      closeExport: 'Fermer l\'export',
      exportPlan: 'Exporter le plan',
      projectName: 'Nom du projet',
      surveyor: 'Géomètre',
      scale: 'Échelle',
      suggested: 'Suggestion',
      apply: 'Appliquer',
      pdfPaper: 'Papier PDF',
      pdfOrientation: 'Orientation PDF',
      landscape: 'Paysage',
      portrait: 'Portrait',
      notes: 'Notes',
      projectPlaceholder: 'Plan topographique',
      surveyorPlaceholder: 'Nom / équipe',
      scalePlaceholder: 'Exemple : 1:500',
      notesPlaceholder: 'Notes de site, remarques de datum, contrôles qualité...',
      exportPng: 'Exporter en PNG',
      exportPdf: 'Exporter en PDF',
      mapNotReady: 'La carte n\'est pas encore prête. Réessayez dans un instant.',
      mapExportFailed: 'Échec de l\'export de la carte : {{message}}',
    },
    converter: {
      quickActions: 'Actions rapides',
      goToBulk: 'Aller au lot',
      goToExports: 'Aller aux exports',
      resetBulk: 'Réinitialiser le lot',
      singlePointConversion: 'Conversion d\'un point unique',
      inputFormat: 'Format d\'entrée :',
      outputFormat: 'Format de sortie :',
      decimalDegrees: 'Degrés décimaux (DD)',
      degreesMinutesSeconds: 'Degrés/Minutes/Secondes (DMS)',
      bothDdAndDms: 'DD et DMS',
      inputFormatHintDms: 'Formats : 48°51\'24"N, 48:51:24 ou 48 51 24',
      outputFormatHintDms: 'Affiché avec N/S/E/O (ex. : 48°51\'24"N)',
      outputFormatHintBoth: 'Affiche des colonnes séparées pour DD et DMS',
      xLon: 'X / Lon',
      yLat: 'Y / Lat',
      height: 'Hauteur',
      geoidMode: 'Mode géoïde :',
      geoidGrid: 'Grille géoïde :',
      notAvailable: 'N/D',
      convertSinglePoint: 'Convertir le point',
      detecting: 'Détection...',
      detectCrs: 'Détecter le SCR',
      resetSingle: 'Réinitialiser le point',
      confidenceScale: 'Échelle de confiance',
      confidenceHigh: '90-100 % : élevée - correspondance par emprise',
      confidenceGood: '75-89 % : bonne - correspondance UTM/métadonnées',
      confidenceFair: '60-74 % : moyenne - transformation d\'essai',
      confidenceLow: 'Sous 60 % : faible - à utiliser avec prudence',
      detectedCrsSuggestions: 'Suggestions de SCR détectés',
      topDetectionsOnly: 'Meilleures détections uniquement',
      allDetections: 'Toutes les détections',
      expandList: 'Développer la liste',
      compactList: 'Réduire la liste',
      plotOnMap: 'Tracer sur la carte',
      topModeShows: 'Le mode principal affiche et trace les {{count}} détections les plus fiables.',
      allModePlots: 'Le mode complet trace les {{count}} détections.',
      lowConfidenceWarning: 'Détection à faible confiance. Vérifiez les 3 premières suggestions et tracez-les sur la carte avant d\'appliquer.',
      use: 'Utiliser',
      showingSuggestions: 'Affichage de {{visible}} suggestion(s) sur {{total}}. Utilisez Développer la liste pour voir le classement complet.',
      bulkConversionImport: 'Conversion / import par lot',
      hide: 'Masquer',
      show: 'Afficher',
      bulkInputToggle: '{{action}} la saisie en lot (un point par ligne : [ID] x y [z])',
      uploading: 'Téléversement',
      uploadBulkFile: 'Téléverser un fichier en lot (CSV/TXT/GeoJSON/GPX/KML/KMZ/ZIP/XLSX)',
      chooseFile: 'Choisir un fichier',
      loadDwgSample: 'Charger l\'exemple DWG',
      convertFileBulk: 'Convertir le fichier / lot',
      detectCrsVisualizeOnlyTitle: 'Détecter le SCR + visualiser seulement',
      detectCrsVisualizeOnlyDescription: 'Détecte automatiquement le système de coordonnées du fichier DXF ou DWG chargé et affiche sa géométrie directement sur la carte sans conversion. Utilisez ceci pour inspecter la position d\'origine du fichier et vérifier son SCR avant conversion.',
      preparingPreview: 'Préparation de l\'aperçu...',
      detectCrsVisualizeOnly: 'Détecter le SCR + visualiser seulement',
      downloadCadSummaryTitle: 'Télécharger le rapport de synthèse CAO',
      downloadCadSummaryDescription: 'Génère et télécharge un rapport texte lisible des résultats d\'inspection du fichier CAO. Inclut les couches, nombres d\'entités, SCR détecté, avertissements et réparations appliquées pendant l\'import.',
      downloadCadSummary: 'Télécharger la synthèse CAO',
      downloadRawCadDebugTitle: 'Télécharger le JSON brut de debug CAO',
      downloadRawCadDebugDescription: 'Télécharge la charge utile JSON complète renvoyée par le parseur CAO. Destiné au support technique et au débogage, avec tous les champs internes renvoyés par le serveur.',
      downloadRawCadDebug: 'Télécharger le debug CAO brut',
      cadInspectionValidation: 'Inspection et validation CAO',
      selectCadFileHint: 'Sélectionnez un fichier DXF ou DWG, puis utilisez Détecter le SCR + visualiser seulement (aperçu) ou Convertir le fichier / lot pour inspecter le routage, le SCR détecté et les limites analysées.',
      benchmarkReferenceValidation: 'Benchmark / validation de référence',
      geoidReadyBanner: 'Conversion 3D prête. Les grilles géoïdes se chargeront automatiquement au besoin.',
      loadedGrids: 'Grilles chargées : {{value}}',
      none: 'aucune',
      ready: 'prête',
      autoDetected: 'SCR détecté automatiquement',
      detectedTop: 'Nous avons détecté ces {{count}} systèmes de coordonnées les plus plausibles. Cliquez sur une option ci-dessous pour la choisir :',
      whyRankedFirst: 'Pourquoi {{code}} est classé en tête',
      whyNotSecond: 'Pourquoi pas le n°2 ?',
      selected: 'SÉLECTIONNÉ',
      match: '{{count}}% de correspondance',
      fromCrs: 'SCR source',
      toCrs: 'SCR cible',
      swapCrsTitle: 'Inverser SCR source / cible',
      swapCrsDescription: 'Inverse les systèmes de coordonnées source et cible. Pratique pour lancer rapidement la conversion inverse.',
      swapCrsAria: 'Inverser le SCR source et le SCR cible',
      undoAction: 'Annuler',
      redoAction: 'Rétablir',
      projectPresets: 'Préréglages projet',
      summary: {
        high: 'Confiance élevée',
        good: 'Bonne confiance',
        moderate: 'Confiance modérée',
        low: 'Faible confiance',
        primarySignal: 'Signal principal : {{reason}}',
        rankingStrength: 'Force du classement : {{label}} ({{percent}}%).',
        gapClear: 'Écart avec le candidat suivant : {{points}} points. Le choix est net.',
        gapReview: 'Écart avec le candidat suivant : {{points}} points. Le choix est cohérent mais mérite une vérification rapide.',
        gapManual: 'Écart avec le candidat suivant : {{points}} points. Les meilleurs candidats sont proches, une confirmation manuelle est recommandée.',
        geographicPenalty: 'Filtre métier appliqué : les SCR projetés ont été déclassés car l\'entrée ressemble à des coordonnées géographiques en degrés.',
        projectedPenalty: 'Filtre métier appliqué : les SCR géographiques ont été déclassés car l\'entrée ressemble à des coordonnées projetées en mètres.',
        comparison: '{{top}} est resté devant {{second}} avec un écart de {{points}} points. Signal du n°2 : {{reason}}',
      },
    },
    panels: {
      searchTitle: 'Recherche et filtre des points',
      searchPlaceholder: 'Rechercher par nom, ID...',
      crs: 'SCR',
      allCrs: 'Tous les SCR',
      sourceType: 'Type de source',
      allTypes: 'Tous les types',
      hideAdvanced: 'Masquer les options avancées',
      showAdvanced: 'Afficher les options avancées',
      elevationMin: 'Altitude min (m)',
      elevationMax: 'Altitude max (m)',
      min: 'Min',
      max: 'Max',
      matchingPoints: 'Correspondance : {{count}} / {{total}} points',
      applyFilter: 'Appliquer le filtre',
      clear: 'Effacer',
      multiMeasurementsTitle: 'Mesures multipoints',
      live: 'Temps réel',
      pointsShort: 'pts',
      distance: 'Distance',
      avgElevation: 'Alt. moy.',
      gain: 'Gain',
      loss: 'Perte',
      minElevation: 'Alt. min',
      maxElevation: 'Alt. max',
      area: 'Aire',
      perimeter: 'Périmètre',
      closePolygon: 'Fermer le polygone',
      exportProfile: 'Exporter le profil',
      measurementNamePlaceholder: 'Nommer cette mesure...',
      save: 'Enregistrer',
      saved: 'Enregistré',
      listView: 'Vue liste',
      compareTable: 'Tableau comparatif',
      exportSavedCsv: 'Exporter le CSV enregistré',
      enableMeasure: 'Activez le mode mesure et cliquez sur 2 points ou plus pour commencer',
      batchOperationsTitle: 'Opérations par lot',
      pointsSelectedFromTotal: '{{count}} points sélectionnés sur {{total}} au total',
      pointsTotal: '{{total}} points au total',
      operation: 'Opération',
      selectOperation: 'Sélectionner une opération',
      viewStatistics: 'Voir les statistiques',
      exportCsv: 'Exporter en CSV',
      addElevationOffset: 'Ajouter un décalage altimétrique',
      deleteSelected: 'Supprimer la sélection',
      elevationOffset: 'Décalage altimétrique (m)',
      elevationOffsetExample: 'ex. 2.5 ou -1.5',
      addOffsetToPoints: 'Ajout de {{offset}} m à l\'altitude des {{count}} points',
      deleteWarning: 'Cela supprimera définitivement {{count}} point(s). Cette action est irréversible.',
      confirmDelete: 'Confirmer la suppression',
      yesDelete: 'Oui, supprimer',
      cancel: 'Annuler',
      exportPoints: 'Exporter {{count}} points',
      applyOffset: 'Appliquer le décalage à {{count}} points',
      selectOperationAbove: 'Sélectionnez une opération ci-dessus',
      invalidElevationOffset: 'Décalage altimétrique invalide',
      batchStatsTitle: 'Statistiques par lot',
      elevations: 'Altitudes',
      avg: 'Moy.',
      crsDistribution: 'Répartition des SCR',
      sourceTypes: 'Types de source',
      diagnosticsTitle: 'Diagnostic de performance',
      healthLarge: 'VOLUMINEUX',
      healthModerate: 'MODÉRÉ',
      healthGood: 'BON',
      data: 'Données',
      performance: 'Performance',
      points: 'Points',
      lines: 'Lignes',
      polylines: 'Polylignes',
      arcs: 'Arcs',
      circles: 'Cercles',
      ellipses: 'Ellipses',
      splines: 'Splines',
      bulgeArcs: 'Arcs bulge',
      proxyCurves: 'Courbes proxy',
      approxCurves: 'Courbes approx.',
      vertices: 'Sommets',
      memory: 'Mémoire',
      render: 'Rendu',
      fps: 'FPS',
      optimizationTips: 'Conseils d\'optimisation',
      tipsLargePointCount: 'Grand nombre de points : activer le suppressseur de doublons ou filtrer les points',
      tipsManyVertices: 'Beaucoup de sommets : la géométrie CAO est complexe ; dézoomez pour un rendu plus rapide',
      tipsHighMemory: 'Utilisation mémoire élevée : envisagez de découper le fichier',
      tipsLowFps: 'FPS faible : essayez de désactiver les libellés ou de zoomer sur une zone précise',
      dxfLayersTitle: 'Couches DXF',
      noDxfLayerData: 'Aucune donnée de couche DXF disponible. Importez un DXF ou un DWG pour voir son arborescence de couches.',
      visibleFraction: '{{visible}} / {{total}} visibles',
      declared: 'Déclarées',
      standardized: 'Standardisées',
      renamed: 'Renommées',
      showAllLayers: 'Afficher toutes les couches',
      showAllLayersDescription: 'Rend toutes les couches DXF visibles simultanément sur la carte.',
      hideAllLayers: 'Masquer toutes les couches',
      hideAllLayersDescription: 'Masque toutes les couches DXF d\'un seul coup sur la carte.',
      showAll: 'Tout afficher',
      hideAll: 'Tout masquer',
      totalEntities: 'Entités totales',
      textEntities: 'Entités texte',
      toggleLayerTitle: 'Basculer la couche : {{name}}\nNoms d\'origine : {{originalNames}}',
      elevationProfileTitle: 'Profil altimétrique',
      addMeasurementPoints: 'Ajoutez 2 points de mesure ou plus pour générer le profil',
      coverage: 'Couverture',
      measuredPointHeights: 'Altitudes mesurées des points',
      onlineProfileUnavailable: 'Impossible de récupérer le profil altimétrique en ligne.',
      terrainProfile: 'Profil terrain IGN GéoPlateforme',
      fallbackHeights: 'Repli : altitudes des points sélectionnés uniquement',
      sampledElevations: '{{count}} altitudes échantillonnées',
      selectedPoints: '{{count}} points sélectionnés',
      loadingTerrain: 'Chargement des échantillons terrain...',
      elevation: 'Altitude',
      total: 'Total',
      samples: 'Échantillons',
      selected: 'Sélectionnés',
      terrainChange: 'Variation du terrain',
      slope: 'Pente',
      markerStylesTitle: 'Styles de marqueurs et légende',
      colorTab: 'Couleur',
      iconsTab: 'Icônes',
      legendTab: 'Légende',
      colorByElevation: 'Colorer les points selon des règles d\'altitude',
      pointSizeScale: 'Échelle de taille des points',
      elevationRanges: 'Plages d\'altitude (m)',
      pickColor: 'Choisir une couleur',
      label: 'Libellé',
      newRange: 'Nouvelle plage',
      addRange: 'Ajouter une plage',
      uploadIconsHelp: 'Importer des icônes PNG/SVG pour remplacer les marqueurs circulaires par type de point.',
      upload: 'Importer',
      iconsRenderSize: 'Les icônes s\'affichent en 24x24 px sur la carte.',
      showLegendOverlay: 'Afficher la légende sur la carte',
      legendPreview: 'Aperçu de la légende',
      customIcons: 'Icônes personnalisées',
      elevationColors: 'Couleurs d\'altitude',
      legendEmpty: 'Activez les règles de couleur altimétriques ou importez des icônes pour remplir la légende.',
      smartConflictTitle: 'Détection intelligente des conflits',
      issueTypes: '{{count}} type(s) de problème',
      noConflicts: 'Aucun conflit',
      pointsChecked: 'Points contrôlés',
      axisAlerts: 'Alertes d\'axes',
      duplicatePointIds: 'IDs de points dupliqués',
      duplicatePointIdsDetail: '{{count}} valeur(s) d\'ID exact dupliquées.',
      duplicateLogicalIds: 'IDs logiques dupliqués entre fichiers',
      duplicateLogicalIdsDetail: '{{count}} valeur(s) d\'ID de base répétées après suppression du préfixe source.',
      overlapElevations: 'Points superposés avec altitudes différentes',
      overlapElevationsDetail: '{{count}} groupe(s) de coordonnées superposées présentent un écart altimétrique >= 0.5 m.',
      inconsistentHeightUnits: 'Unités d\'altitude potentiellement incohérentes',
      inconsistentHeightUnitsDetail: '{{count}} groupe(s) de recouvrement contiennent des paires de hauteurs proches du ratio mètre/pied.',
      inconsistentHeightUnitsMax: 'Des valeurs absolues d\'altitude très élevées ont été détectées (max |Z| {{value}}).',
      mixedAxisOrder: 'Ordre d\'axes potentiellement mixte',
      mixedAxisOrderImpossible: '{{count}} point(s) dépassent les bornes valides lat/lon.',
      mixedAxisOrderSwap: '{{count}} paire(s) de coordonnées semblent inversées (lat/lon et lon/lat).',
      topDuplicateIds: 'Principaux IDs dupliqués',
      largestOverlapDelta: 'Plus grand écart altimétrique en recouvrement',
      noMajorConflicts: 'Aucun conflit majeur d\'ID, de recouvrement, d\'unité ou d\'ordre d\'axes n\'a été détecté sur les points visibles.',
      hatchAreasTitle: 'Aires de hachures',
      noHatches: 'Aucune entité HATCH trouvée. Importez un fichier DXF avec des zones hachurées pour calculer les aires.',
      regionsCount: '{{count}} région{{suffix}}',
      totalEnclosedArea: 'Aire totale fermée',
      layer: 'Couche',
      solid: 'PLEIN',
      dxfDiffTitle: 'Diff DXF',
      compareComplete: 'Comparaison terminée',
      baselineOriginal: 'Référence (A - original)',
      revisedCurrent: 'Révision (B - courant)',
      loadingDxf: 'Chargement du DXF...',
      failedToLoadFile: 'Échec du chargement de {{name}} : {{message}}',
      changesDetected: 'Changements détectés (tolérance coordonnée : {{tolerance}} m) :',
      added: '{{count}} ajouté(s)',
      removed: '{{count}} supprimé(s)',
      unchanged: '{{count}} inchangé(s)',
      identicalFiles: 'Les fichiers sont géométriquement identiques (dans la tolérance)',
      changesVerdict: '{{lineChanges}} changement(s) de ligne/polyligne et {{pointChanges}} changement(s) de point détecté(s)',
      entityBreakdownTitle: 'Répartition des entités',
      importCadForEntityStats: 'Importez un DXF ou un DWG pour voir les statistiques des types d\'entités.',
      entitiesCount: '{{count}} entités',
      noEntitiesFound: 'Aucune entité trouvée dans le fichier chargé.',
      moreLayers: '+ plus de couches...',
      entityPickerTitle: 'Sélecteur d\'entités',
      active: 'Actif',
      clickEntityToInspect: 'Cliquez sur une ligne ou une polyligne CAO sur la carte pour inspecter ses propriétés.',
      type: 'Type',
      color: 'Couleur',
      source: 'Source',
      length: 'Longueur',
      mapUnits: 'unités carte',
      verticesLabel: 'Sommets',
      handle: 'Handle',
    },
    common: {
      yes: 'Oui',
      no: 'Non',
      none: 'Aucun',
      unknown: 'Inconnu',
      file: 'Fichier',
      type: 'Type',
      generated: 'Généré',
    },
    errors: {
      unexpectedRender: 'Erreur de rendu inattendue.',
      failedToRender: '{{label}} n\'a pas pu s\'afficher',
      retry: 'Réessayer',
      copied: 'Copié',
      copyError: 'Copier l\'erreur',
      backendUnavailable: 'L\'import DWG natif nécessite le service backend CAD. Cible actuelle de l\'API CAD : {{target}}. Utilisez l\'API CAD hébergée ou lancez "npm run dev:server" en local.',
      invalidChunkPlan: 'Impossible de construire un plan de téléversement CAD valide.',
      chunkUploadFailed: 'Échec du téléversement du bloc {{index}}/{{total}}.',
      chunkFinalizeFailed: 'Échec de la finalisation du téléversement CAD par blocs.',
      fileTooLargeCad: 'Le fichier "{{name}}" fait {{size}} MB, ce qui dépasse la limite de téléversement de {{limit}} MB. Réduisez la taille du fichier ou découpez-le en plusieurs dessins.',
      uploadProgressUploading: 'Téléversement de {{size}} MB vers le backend CAD...',
      uploadProgressWaiting: 'En attente du démarrage de la conversion DWG vers DXF...',
      uploadProgressConverting: 'Conversion du fichier DWG en cours - cela peut prendre 20 à 60 s pour les grands dessins...',
      uploadProgressStillConverting: 'Conversion toujours en cours - les dessins complexes peuvent prendre jusqu\'à 2 minutes...',
      uploadProgressAlmostDone: 'Presque terminé - analyse de la géométrie convertie...',
      uploadProgressChunked: 'Grand fichier CAD détecté ({{size}} MB). Passage en mode téléversement par blocs ({{mode}}).',
      uploadProgressFallback: 'Le téléversement par blocs n\'est pas disponible sur ce backend. Retour au téléversement direct...',
      uploadProgressComplete: 'Téléversement terminé. Finalisation et analyse de la géométrie CAD...',
      uploadProgressRefining: 'Aperçu CAD rapide prêt. Raffinement de la géométrie complète en cours...',
      uploadTimeout: 'Le backend CAD n\'a pas répondu dans les {{seconds}} secondes. Cela peut arriver avec des DWG très complexes. Réessayez l\'import ou activez manuellement l\'aperçu points seuls si nécessaire.',
      invalidCadResponse: 'Le backend CAD a renvoyé une réponse invalide.',
      cadHealthFailed: 'Le contrôle de santé du backend CAD a échoué pour {{target}}.',
      fileTooLargeGeneric: 'Le fichier "{{name}}" est trop volumineux ({{size}}). La taille maximale prise en charge pour les fichiers {{type}} est de {{limit}}. Réduisez la taille du fichier ou découpez-le.',
      invalidKmlXml: 'XML KML invalide dans {{source}}',
      kmzMissingKml: 'L\'archive KMZ ne contient pas de document KML.',
      unsupportedDwg: 'Contenu DWG non pris en charge. Le DWG natif nécessite le backend CAD, ou vous pouvez exporter le dessin en DXF puis réessayer.',
      elevationNeedsTwoPoints: 'Au moins deux points de mesure sont nécessaires pour demander un profil altimétrique.',
      ignRequestFailed: 'La requête de profil altimétrique IGN a échoué ({{status}}).',
      ignNotEnoughSamples: 'L\'IGN n\'a pas renvoyé assez d\'échantillons altimétriques pour ce profil.',
      ignProfileBuildFailed: 'Impossible de construire les données du profil à partir des échantillons IGN.',
      elevationNeedsTwoPointsShort: 'Au moins deux points de mesure sont nécessaires.',
      unknownOpenTopoProvider: 'Fournisseur OpenTopoData inconnu : {{providerId}}',
      openTopoProxyFailed: 'La requête proxy OpenTopoData a échoué ({{status}}).',
      openTopoRequestFailed: 'La requête OpenTopoData a échoué ({{status}}).',
      openTopoUnavailable: 'Impossible de récupérer le profil altimétrique OpenTopoData. Vérifiez le routage/CORS de l\'API d\'élévation du backend.',
      openTopoNotEnoughSamples: 'OpenTopoData n\'a pas renvoyé assez d\'échantillons altimétriques pour ce profil.',
      openTopoProfileBuildFailed: 'Impossible de construire les données du profil à partir des échantillons OpenTopoData.',
      notEnoughValidMeasurementPoints: 'Pas assez de points de mesure valides.',
      unknownElevationProvider: 'Fournisseur altimétrique inconnu : {{providerId}}',
      geoidFetchIndexFailed: 'Impossible de récupérer l\'index du géoïde ({{status}})',
      geoidHttpFailed: 'HTTP {{status}} : {{statusText}}',
      geoidEmptyResponse: 'Réponse vide (content-length : {{length}})',
      geoidLoadFailed: 'Échec du chargement de {{name}} depuis {{url}} : {{message}}',
      geoidNoUrl: 'Aucune URL trouvée pour la grille de géoïde {{name}}',
      geoidGridNotLoaded: 'La grille {{name}} n\'est pas chargée',
      geoidRasterReadFailed: 'Impossible de lire la fenêtre raster pour {{name}} en ({{lon}}, {{lat}})',
      geoidGlobalFallbackFailed: 'Impossible de charger une grille géoïde globale. Vérifiez l\'accessibilité des fichiers géoïde.',
    },
    reports: {
      metadataGeneratedAt: 'Généré le',
      metadataFromCrs: 'SCR source',
      metadataToCrs: 'SCR cible',
      metadataGeoidMode: 'Mode géoïde',
      metadataGeoidName: 'Grille géoïde',
      metadataAccuracy: 'Précision estimée (cm)',
      metadataConfidence: 'Confiance',
      metadataTotalRows: 'Nombre total de lignes',
      metadataSuccessRows: 'Lignes réussies',
      metadataErrorRows: 'Lignes en erreur',
      confidenceLocal: 'Local / non géoréférencé',
      confidenceNeedsReview: 'Vérification requise',
      confidenceHigh: 'Confiance élevée',
      confidenceMedium: 'Confiance moyenne',
      confidenceLow: 'Confiance faible',
      cadSummaryTitle: 'Rapport de synthèse CAD',
      cadSummarySubtitle: 'Diagnostic d\'import lisible pour l\'utilisateur pour revue DWG/DXF.',
      overview: 'Vue d\'ensemble',
      warnings: 'Avertissements',
      unresolvedXrefs: 'XREF non résolues',
      missingBlocks: 'Blocs manquants',
      cyclicBlocks: 'Blocs cycliques',
      recommendations: 'Recommandations',
      technicalDetail: 'Détail technique',
      importNotice: 'Notice d\'import',
      processingMode: 'Mode de traitement',
      processingRoute: 'Chemin de traitement',
      rowsExtracted: 'Lignes extraites',
      detectedCrs: 'SCR détecté',
      backendMode: 'Mode backend',
      usedConverter: 'Convertisseur utilisé',
      axisNormalization: 'Normalisation des axes',
      axisNormalized: 'Axes source inversés corrigés automatiquement',
      noWarnings: 'Aucun avertissement n\'a été généré pour cet import CAD.',
      noMajorWarnings: 'Aucun avertissement CAD majeur n\'a été détecté pendant cette exécution.',
      integrityVerified: 'Intégrité vérifiée',
      serverPreScanRisk: 'Risque de pré-analyse serveur',
      serverRecommendedEngine: 'Moteur recommandé par le serveur',
      crsConfidence: 'Confiance SCR',
      preflightConfidence: 'Confiance de prévol',
      generated: 'Généré',
      referenceConfidence: 'Confiance de référencement',
      expandedInserts: 'Insertions développées',
      flattenedEntities: 'Entités aplaties',
      nestedBlockDepth: 'Profondeur max. des blocs imbriqués',
      technicalDetailHint: 'Pour l\'assistance ingénierie, utilisez l\'export JSON brut séparé.',
    },
    providers: {
      ignLabel: 'IGN GéoPlateforme',
      ignDescription: 'France - RGE ALTI / BD ALTI, résolution 1 à 25 m',
      ignCoverage: 'France (meilleure précision)',
      srtmLabel: 'OpenTopoData - SRTM 30 m',
      srtmDescription: 'Monde (~60N à 60S), USGS SRTM, résolution ~30 m',
      srtmCoverage: 'Monde (lat -60 à +60)',
      asterLabel: 'OpenTopoData - ASTER 30 m',
      asterDescription: 'Monde, NASA ASTER, résolution ~30 m',
      asterCoverage: 'Monde',
      eudemLabel: 'OpenTopoData - EU-DEM 25 m',
      eudemDescription: 'Europe, EEA EU-DEM, résolution ~25 m',
      eudemCoverage: 'Europe',
      measuredLabel: 'Altitudes mesurées uniquement',
      measuredDescription: 'Utilise les hauteurs ellipsoïdales/orthométriques des points sélectionnés (sans MNT)',
      measuredCoverage: 'Partout - hors ligne',
      measuredSourceLabel: 'Altitudes mesurées des points',
      ignSourceLabel: 'Profil IGN GéoPlateforme',
      sampleLabel: 'Échantillon {{index}}',
      pointLabel: 'Point {{index}}',
      openTopoSourceLabel: 'OpenTopoData - {{dataset}}',
    },
  },
};

const resolvePath = (object, path) => path.split('.').reduce((acc, key) => (acc && acc[key] !== undefined ? acc[key] : undefined), object);

export const createTranslator = (language = 'en') => {
  const activeLanguage = UI_COPY[language] ? language : 'en';
  return (path, replacements = {}) => {
    const template = resolvePath(UI_COPY[activeLanguage], path) ?? resolvePath(UI_COPY.en, path) ?? path;
    if (typeof template !== 'string') return template;
    return template.replace(/\{\{\s*(\w+)\s*\}\}/g, (_, key) => {
      const value = replacements[key];
      return value === undefined || value === null ? '' : String(value);
    });
  };
};

export const setCurrentUiLanguage = (language = 'en') => {
  currentUiLanguage = UI_COPY[language] ? language : 'en';
};

export const getCurrentUiLanguage = () => currentUiLanguage;

export const translateUi = (path, replacements = {}) => createTranslator(currentUiLanguage)(path, replacements);