export const UI_LANGUAGE_STORAGE_KEY = 'surveycalc.uiLanguage';

export const UI_LANGUAGE_OPTIONS = [
  { code: 'en', label: 'EN' },
  { code: 'fr', label: 'FR' },
];

const UI_COPY = {
  en: {
    header: {
      kicker: 'Professional Geomatics Platform',
      subtitle: 'Coordinate Conversion, CRS Detection, Benchmarking, and Survey Computation Workspace',
      language: 'Interface language',
    },
    footer: {
      copyright: 'Survey Calculator | MIT License',
      terms: 'Terms of Service',
      security: 'Security',
      github: 'GitHub (Profile)',
      openSource: 'Open Source',
      request: 'Request Code or Website (Email)',
      madeBy: 'Made by',
    },
    app: {
      currentSession: 'Current Session',
      interactiveMap: 'Interactive Map',
      newOperation: 'New Operation',
      newOperationTitle: 'New Operation',
      newOperationDescription: 'Resets the entire workspace for a fresh session. Clears all loaded points, CAD geometry, measurements, and panel states. Use this when starting a brand-new survey project.',
      clearMeasurementsTitle: 'Clear Measurements',
      clearMeasurementsDescription: 'Removes all currently placed measurement points from the map. Use this to start a fresh distance or area measurement from scratch.',
      clear: 'Clear',
      undoTitle: 'Undo Last Point (Ctrl+Z)',
      undoDescription: 'Removes the most recently placed measurement point. Step back through your clicks one at a time to correct mistakes without losing all measurements.',
      undo: 'Undo',
      redoTitle: 'Redo Point (Ctrl+Y)',
      redoDescription: 'Re-applies a previously undone measurement point. Use after Undo if you removed a point by mistake.',
      redo: 'Redo',
      closePolygonTitle: 'Close Polygon',
      closePolygonDescription: 'Connects the last measurement point back to the first to close the polygon. Once closed, the tool calculates total perimeter and enclosed area automatically.',
      close: 'Close',
      measureToolTitle: 'Measure Tool',
      measuringTitle: 'Measuring - Click to Stop',
      measureActiveDescription: 'Measurement mode is active. Click converted points on the map to drop pins. The tool computes distance, bearing, and cumulative length for each leg. Click again to deactivate.',
      measureInactiveDescription: 'Activates measurement mode. Once active, click any converted point on the map to start placing measurement pins. Distances, bearings, and running totals are calculated in real time.',
      measure: 'Measure',
      measuring: 'Measuring...',
      mapFocus: 'Map Focus',
      balancedView: 'Balanced View',
      balancedViewDescription: 'Restores the balanced split layout where the coordinate converter panel and the map share equal screen space.',
      mapFocusDescription: 'Expands the map to occupy most of the screen, hiding side panels for an unobstructed view of your survey data. Click again to restore the balanced layout.',
      projectLayers: 'Project Layers',
      showAll: 'Show all',
      hideAll: 'Hide all',
      measureResults: 'Measure Results',
      distance: 'Distance',
      angle: 'Angle',
      meters: 'meters',
      kilometers: 'kilometers',
      degree: 'degree (°)',
      measureHint: 'Click converted map points to add measure points (3+ for polygon area)',
      measureEmpty: 'Turn on Measure, then click two converted points on the map.',
      convertedPoint: 'Converted point',
      clickSecondPoint: 'Click a second converted point for P2',
    },
    converter: {
      quickActions: 'Quick Actions',
      goToBulk: 'Go to Bulk',
      goToExports: 'Go to Exports',
      resetBulk: 'Reset Bulk',
      autoDetected: 'CRS Auto-Detected',
      detectedTop: 'We detected these top {{count}} coordinate systems. Click any option below to choose it:',
      whyRankedFirst: 'Why {{code}} is ranked first',
      whyNotSecond: 'Why not #2?',
      selected: 'SELECTED',
      match: '{{count}}% match',
      fromCrs: 'From CRS',
      toCrs: 'To CRS',
      swapCrsTitle: 'Swap From / To CRS',
      swapCrsDescription: 'Swaps the source (From) and target (To) coordinate reference systems. Useful when you need to reverse a conversion - for example switching from RGF93 -> WGS84 to WGS84 -> RGF93 in one click.',
      swapCrsAria: 'Swap From and To CRS',
      undoAction: 'Undo',
      redoAction: 'Redo',
      projectPresets: 'Project Presets',
      summary: {
        high: 'High confidence',
        good: 'Good confidence',
        moderate: 'Moderate confidence',
        low: 'Low confidence',
        primarySignal: 'Primary signal: {{reason}}',
        rankingStrength: 'Ranking strength: {{label}} ({{percent}}%).',
        gapClear: 'Top-vs-next gap: {{points}} points. This is a clear winner.',
        gapReview: 'Top-vs-next gap: {{points}} points. Selection is reasonable but still worth a quick review.',
        gapManual: 'Top-vs-next gap: {{points}} points. The top candidates are close, so manual confirmation is recommended.',
        geographicPenalty: 'Domain filter applied: projected candidates were down-ranked because the input behaves like geographic lon/lat degrees.',
        projectedPenalty: 'Domain filter applied: geographic candidates were down-ranked because the input behaves like projected metric coordinates.',
        comparison: '{{top}} was kept above {{second}} by a {{points}}-point margin. #2 signal: {{reason}}',
      },
    },
  },
  fr: {
    header: {
      kicker: 'Plateforme professionnelle de géomatique',
      subtitle: 'Conversion de coordonnées, détection de SCR, benchmarking et espace de calcul topographique',
      language: 'Langue de l\'interface',
    },
    footer: {
      copyright: 'Survey Calculator | Licence MIT',
      terms: 'Conditions d\'utilisation',
      security: 'Sécurité',
      github: 'GitHub (Profil)',
      openSource: 'Open source',
      request: 'Demander le code ou un site web (e-mail)',
      madeBy: 'Réalisé par',
    },
    app: {
      currentSession: 'Session en cours',
      interactiveMap: 'Carte interactive',
      newOperation: 'Nouvelle opération',
      newOperationTitle: 'Nouvelle opération',
      newOperationDescription: 'Réinitialise tout l\'espace de travail pour une nouvelle session. Efface les points chargés, la géométrie CAO, les mesures et l\'état des panneaux.',
      clearMeasurementsTitle: 'Effacer les mesures',
      clearMeasurementsDescription: 'Supprime tous les points de mesure actuellement placés sur la carte pour recommencer une mesure.',
      clear: 'Effacer',
      undoTitle: 'Annuler le dernier point (Ctrl+Z)',
      undoDescription: 'Supprime le point de mesure placé le plus récemment, sans perdre l\'ensemble du tracé.',
      undo: 'Annuler',
      redoTitle: 'Rétablir le point (Ctrl+Y)',
      redoDescription: 'Rétablit un point de mesure précédemment annulé.',
      redo: 'Rétablir',
      closePolygonTitle: 'Fermer le polygone',
      closePolygonDescription: 'Relie le dernier point de mesure au premier pour fermer le polygone et calculer automatiquement le périmètre et l\'aire.',
      close: 'Fermer',
      measureToolTitle: 'Outil de mesure',
      measuringTitle: 'Mesure en cours - cliquer pour arrêter',
      measureActiveDescription: 'Le mode mesure est actif. Cliquez sur les points convertis de la carte pour poser des repères. L\'outil calcule distance, gisement et cumul pour chaque segment.',
      measureInactiveDescription: 'Active le mode mesure. Une fois actif, cliquez sur un point converti de la carte pour commencer à placer des repères.',
      measure: 'Mesurer',
      measuring: 'Mesure...',
      mapFocus: 'Focus carte',
      balancedView: 'Vue équilibrée',
      balancedViewDescription: 'Restaure la mise en page équilibrée où le convertisseur et la carte partagent l\'écran.',
      mapFocusDescription: 'Agrandit la carte pour occuper l\'essentiel de l\'écran et masquer les panneaux latéraux.',
      projectLayers: 'Couches du projet',
      showAll: 'Tout afficher',
      hideAll: 'Tout masquer',
      measureResults: 'Résultats de mesure',
      distance: 'Distance',
      angle: 'Angle',
      meters: 'mètres',
      kilometers: 'kilomètres',
      degree: 'degré (°)',
      measureHint: 'Cliquer sur les points convertis de la carte pour ajouter des points de mesure (3+ pour une aire)',
      measureEmpty: 'Activez Mesurer, puis cliquez sur deux points convertis de la carte.',
      convertedPoint: 'Point converti',
      clickSecondPoint: 'Cliquez sur un deuxième point converti pour P2',
    },
    converter: {
      quickActions: 'Actions rapides',
      goToBulk: 'Aller au lot',
      goToExports: 'Aller aux exports',
      resetBulk: 'Réinitialiser le lot',
      autoDetected: 'SCR détecté automatiquement',
      detectedTop: 'Nous avons détecté ces {{count}} systèmes de coordonnées les plus plausibles. Cliquez sur une option ci-dessous pour la choisir :',
      whyRankedFirst: 'Pourquoi {{code}} est classé en tête',
      whyNotSecond: 'Pourquoi pas le n°2 ?',
      selected: 'SÉLECTIONNÉ',
      match: '{{count}}% de correspondance',
      fromCrs: 'SCR source',
      toCrs: 'SCR cible',
      swapCrsTitle: 'Inverser SCR source / cible',
      swapCrsDescription: 'Inverse les systèmes de coordonnées source et cible. Pratique pour lancer rapidement la conversion inverse.',
      swapCrsAria: 'Inverser le SCR source et le SCR cible',
      undoAction: 'Annuler',
      redoAction: 'Rétablir',
      projectPresets: 'Préréglages projet',
      summary: {
        high: 'Confiance élevée',
        good: 'Bonne confiance',
        moderate: 'Confiance modérée',
        low: 'Faible confiance',
        primarySignal: 'Signal principal : {{reason}}',
        rankingStrength: 'Force du classement : {{label}} ({{percent}}%).',
        gapClear: 'Écart avec le candidat suivant : {{points}} points. Le choix est net.',
        gapReview: 'Écart avec le candidat suivant : {{points}} points. Le choix est cohérent mais mérite une vérification rapide.',
        gapManual: 'Écart avec le candidat suivant : {{points}} points. Les meilleurs candidats sont proches, une confirmation manuelle est recommandée.',
        geographicPenalty: 'Filtre métier appliqué : les SCR projetés ont été déclassés car l\'entrée ressemble à des coordonnées géographiques en degrés.',
        projectedPenalty: 'Filtre métier appliqué : les SCR géographiques ont été déclassés car l\'entrée ressemble à des coordonnées projetées en mètres.',
        comparison: '{{top}} est resté devant {{second}} avec un écart de {{points}} points. Signal du n°2 : {{reason}}',
      },
    },
  },
};

const resolvePath = (object, path) => path.split('.').reduce((acc, key) => (acc && acc[key] !== undefined ? acc[key] : undefined), object);

export const createTranslator = (language = 'en') => {
  const activeLanguage = UI_COPY[language] ? language : 'en';
  return (path, replacements = {}) => {
    const template = resolvePath(UI_COPY[activeLanguage], path) ?? resolvePath(UI_COPY.en, path) ?? path;
    if (typeof template !== 'string') return template;
    return template.replace(/\{\{\s*(\w+)\s*\}\}/g, (_, key) => {
      const value = replacements[key];
      return value === undefined || value === null ? '' : String(value);
    });
  };
};