export const UI_LANGUAGE_STORAGE_KEY = 'surveycalc.uiLanguage';

export const UI_LANGUAGE_OPTIONS = [
  { code: 'en', label: 'EN' },
  { code: 'fr', label: 'FR' },
];

const UI_COPY = {
  en: {
    header: {
      kicker: 'Professional Geomatics Platform',
      subtitle: 'Coordinate Conversion, CRS Detection, Benchmarking, and Survey Computation Workspace',
      language: 'Interface language',
    },
    footer: {
      copyright: 'Survey Calculator | MIT License',
      terms: 'Terms of Service',
      security: 'Security',
      github: 'GitHub (Profile)',
      openSource: 'Open Source',
      request: 'Request Code or Website (Email)',
      madeBy: 'Made by',
    },
    app: {
      currentSession: 'Current Session',
      interactiveMap: 'Interactive Map',
      newOperation: 'New Operation',
      newOperationTitle: 'New Operation',
      newOperationDescription: 'Resets the entire workspace for a fresh session. Clears all loaded points, CAD geometry, measurements, and panel states. Use this when starting a brand-new survey project.',
      clearMeasurementsTitle: 'Clear Measurements',
      clearMeasurementsDescription: 'Removes all currently placed measurement points from the map. Use this to start a fresh distance or area measurement from scratch.',
      clear: 'Clear',
      undoTitle: 'Undo Last Point (Ctrl+Z)',
      undoDescription: 'Removes the most recently placed measurement point. Step back through your clicks one at a time to correct mistakes without losing all measurements.',
      undo: 'Undo',
      redoTitle: 'Redo Point (Ctrl+Y)',
      redoDescription: 'Re-applies a previously undone measurement point. Use after Undo if you removed a point by mistake.',
      redo: 'Redo',
      closePolygonTitle: 'Close Polygon',
      closePolygonDescription: 'Connects the last measurement point back to the first to close the polygon. Once closed, the tool calculates total perimeter and enclosed area automatically.',
      close: 'Close',
      measureToolTitle: 'Measure Tool',
      measuringTitle: 'Measuring - Click to Stop',
      measureActiveDescription: 'Measurement mode is active. Click converted points on the map to drop pins. The tool computes distance, bearing, and cumulative length for each leg. Click again to deactivate.',
      measureInactiveDescription: 'Activates measurement mode. Once active, click any converted point on the map to start placing measurement pins. Distances, bearings, and running totals are calculated in real time.',
      measure: 'Measure',
      measuring: 'Measuring...',
      mapFocus: 'Map Focus',
      balancedView: 'Balanced View',
      balancedViewDescription: 'Restores the balanced split layout where the coordinate converter panel and the map share equal screen space.',
      mapFocusDescription: 'Expands the map to occupy most of the screen, hiding side panels for an unobstructed view of your survey data. Click again to restore the balanced layout.',
      projectLayers: 'Project Layers',
      showAll: 'Show all',
      hideAll: 'Hide all',
      measureResults: 'Measure Results',
      distance: 'Distance',
      angle: 'Angle',
      meters: 'meters',
      kilometers: 'kilometers',
      degree: 'degree (°)',
      measureHint: 'Click converted map points to add measure points (3+ for polygon area)',
      measureEmpty: 'Turn on Measure, then click two converted points on the map.',
      convertedPoint: 'Converted point',
      clickSecondPoint: 'Click a second converted point for P2',
    },
    converter: {
      quickActions: 'Quick Actions',
      goToBulk: 'Go to Bulk',
      goToExports: 'Go to Exports',
      resetBulk: 'Reset Bulk',
      autoDetected: 'CRS Auto-Detected',
      detectedTop: 'We detected these top {{count}} coordinate systems. Click any option below to choose it:',
      whyRankedFirst: 'Why {{code}} is ranked first',
      whyNotSecond: 'Why not #2?',
      selected: 'SELECTED',
      match: '{{count}}% match',
      fromCrs: 'From CRS',
      toCrs: 'To CRS',
      swapCrsTitle: 'Swap From / To CRS',
      swapCrsDescription: 'Swaps the source (From) and target (To) coordinate reference systems. Useful when you need to reverse a conversion - for example switching from RGF93 -> WGS84 to WGS84 -> RGF93 in one click.',
      swapCrsAria: 'Swap From and To CRS',
      undoAction: 'Undo',
      redoAction: 'Redo',
      projectPresets: 'Project Presets',
      summary: {
        high: 'High confidence',
        good: 'Good confidence',
        moderate: 'Moderate confidence',
        low: 'Low confidence',
        primarySignal: 'Primary signal: {{reason}}',
        rankingStrength: 'Ranking strength: {{label}} ({{percent}}%).',
        gapClear: 'Top-vs-next gap: {{points}} points. This is a clear winner.',
        gapReview: 'Top-vs-next gap: {{points}} points. Selection is reasonable but still worth a quick review.',
        gapManual: 'Top-vs-next gap: {{points}} points. The top candidates are close, so manual confirmation is recommended.',
        geographicPenalty: 'Domain filter applied: projected candidates were down-ranked because the input behaves like geographic lon/lat degrees.',
        projectedPenalty: 'Domain filter applied: geographic candidates were down-ranked because the input behaves like projected metric coordinates.',
        comparison: '{{top}} was kept above {{second}} by a {{points}}-point margin. #2 signal: {{reason}}',
      },
    },
    panels: {
      searchTitle: 'Point Search & Filter',
      searchPlaceholder: 'Search by name, ID...',
      crs: 'CRS',
      allCrs: 'All CRS',
      sourceType: 'Source Type',
      allTypes: 'All Types',
      hideAdvanced: 'Hide Advanced',
      showAdvanced: 'Show Advanced',
      elevationMin: 'Elevation Min (m)',
      elevationMax: 'Elevation Max (m)',
      min: 'Min',
      max: 'Max',
      matchingPoints: 'Matching: {{count}} / {{total}} points',
      applyFilter: 'Apply Filter',
      clear: 'Clear',
      multiMeasurementsTitle: 'Multi-Point Measurements',
      live: 'Live',
      pointsShort: 'pts',
      distance: 'Distance',
      avgElevation: 'Avg elev',
      gain: 'Gain',
      loss: 'Loss',
      minElevation: 'Min elev',
      maxElevation: 'Max elev',
      area: 'Area',
      perimeter: 'Perimeter',
      closePolygon: 'Close polygon',
      exportProfile: 'Export profile',
      measurementNamePlaceholder: 'Name this measurement...',
      save: 'Save',
      saved: 'Saved',
      listView: 'List view',
      compareTable: 'Compare table',
      exportSavedCsv: 'Export saved CSV',
      enableMeasure: 'Enable measure mode and click 2+ map points to start measuring',
      batchOperationsTitle: 'Batch Operations',
      pointsSelectedFromTotal: '{{count}} points selected from {{total}} total',
      pointsTotal: '{{total}} points total',
      operation: 'Operation',
      selectOperation: 'Select Operation',
      viewStatistics: 'View Statistics',
      exportCsv: 'Export as CSV',
      addElevationOffset: 'Add Elevation Offset',
      deleteSelected: 'Delete Selected',
      elevationOffset: 'Elevation Offset (m)',
      elevationOffsetExample: 'e.g., 2.5 or -1.5',
      addOffsetToPoints: 'Will add {{offset}} m to all {{count}} point elevation values',
      deleteWarning: 'This will permanently delete {{count}} point(s). This cannot be undone.',
      confirmDelete: 'Confirm Delete',
      yesDelete: 'Yes, Delete',
      cancel: 'Cancel',
      exportPoints: 'Export {{count}} Points',
      applyOffset: 'Apply Offset to {{count}} Points',
      selectOperationAbove: 'Select an operation above',
      invalidElevationOffset: 'Invalid elevation offset',
      batchStatsTitle: 'Batch Statistics',
      elevations: 'Elevations',
      avg: 'Avg',
      crsDistribution: 'CRS Distribution',
      sourceTypes: 'Source Types',
      diagnosticsTitle: 'Performance Diagnostics',
      healthLarge: 'LARGE',
      healthModerate: 'MODERATE',
      healthGood: 'GOOD',
      data: 'Data',
      performance: 'Performance',
      points: 'Points',
      lines: 'Lines',
      polylines: 'Polylines',
      arcs: 'Arcs',
      circles: 'Circles',
      ellipses: 'Ellipses',
      splines: 'Splines',
      bulgeArcs: 'Bulge arcs',
      proxyCurves: 'Proxy curves',
      approxCurves: 'Approx curves',
      vertices: 'Vertices',
      memory: 'Memory',
      render: 'Render',
      fps: 'FPS',
      optimizationTips: 'Optimization Tips',
      tipsLargePointCount: 'Large point count: Enable Duplicate Remover or Filter points',
      tipsManyVertices: 'Many vertices: CAD geometry is complex; zoom out for faster rendering',
      tipsHighMemory: 'High memory usage: Consider splitting into smaller files',
      tipsLowFps: 'Low FPS: Try disabling labels or zooming to specific area',
      dxfLayersTitle: 'DXF Layers',
      noDxfLayerData: 'No DXF layer data available. Import a DXF or DWG file to see its layer tree.',
      visibleFraction: '{{visible}} / {{total}} visible',
      declared: 'Declared',
      standardized: 'Standardized',
      renamed: 'Renamed',
      showAllLayers: 'Show All Layers',
      showAllLayersDescription: 'Makes all DXF layers visible on the map simultaneously. Use this to restore full visibility after selectively hiding individual layers.',
      hideAllLayers: 'Hide All Layers',
      hideAllLayersDescription: 'Hides every DXF layer from the map at once. Useful as a starting point when you want to selectively reveal only specific layers from a complex multi-layer drawing.',
      showAll: 'Show All',
      hideAll: 'Hide All',
      totalEntities: 'Total entities',
      textEntities: 'Text entities',
      toggleLayerTitle: 'Toggle layer: {{name}}\nOriginal names: {{originalNames}}',
      elevationProfileTitle: 'Elevation Profile',
      addMeasurementPoints: 'Add 2+ measurement points to generate profile',
      coverage: 'Coverage',
      measuredPointHeights: 'Measured point heights',
      onlineProfileUnavailable: 'Unable to fetch the online elevation profile.',
      terrainProfile: 'IGN GeoPlateforme terrain profile',
      fallbackHeights: 'Fallback: selected point heights only',
      sampledElevations: '{{count}} sampled elevations',
      selectedPoints: '{{count}} selected points',
      loadingTerrain: 'Loading terrain samples...',
      elevation: 'Elevation',
      total: 'Total',
      samples: 'Samples',
      selected: 'Selected',
      terrainChange: 'Terrain Change',
      slope: 'Slope',
    },
  },
  fr: {
    header: {
      kicker: 'Plateforme professionnelle de géomatique',
      subtitle: 'Conversion de coordonnées, détection de SCR, benchmarking et espace de calcul topographique',
      language: 'Langue de l\'interface',
    },
    footer: {
      copyright: 'Survey Calculator | Licence MIT',
      terms: 'Conditions d\'utilisation',
      security: 'Sécurité',
      github: 'GitHub (Profil)',
      openSource: 'Open source',
      request: 'Demander le code ou un site web (e-mail)',
      madeBy: 'Réalisé par',
    },
    app: {
      currentSession: 'Session en cours',
      interactiveMap: 'Carte interactive',
      newOperation: 'Nouvelle opération',
      newOperationTitle: 'Nouvelle opération',
      newOperationDescription: 'Réinitialise tout l\'espace de travail pour une nouvelle session. Efface les points chargés, la géométrie CAO, les mesures et l\'état des panneaux.',
      clearMeasurementsTitle: 'Effacer les mesures',
      clearMeasurementsDescription: 'Supprime tous les points de mesure actuellement placés sur la carte pour recommencer une mesure.',
      clear: 'Effacer',
      undoTitle: 'Annuler le dernier point (Ctrl+Z)',
      undoDescription: 'Supprime le point de mesure placé le plus récemment, sans perdre l\'ensemble du tracé.',
      undo: 'Annuler',
      redoTitle: 'Rétablir le point (Ctrl+Y)',
      redoDescription: 'Rétablit un point de mesure précédemment annulé.',
      redo: 'Rétablir',
      closePolygonTitle: 'Fermer le polygone',
      closePolygonDescription: 'Relie le dernier point de mesure au premier pour fermer le polygone et calculer automatiquement le périmètre et l\'aire.',
      close: 'Fermer',
      measureToolTitle: 'Outil de mesure',
      measuringTitle: 'Mesure en cours - cliquer pour arrêter',
      measureActiveDescription: 'Le mode mesure est actif. Cliquez sur les points convertis de la carte pour poser des repères. L\'outil calcule distance, gisement et cumul pour chaque segment.',
      measureInactiveDescription: 'Active le mode mesure. Une fois actif, cliquez sur un point converti de la carte pour commencer à placer des repères.',
      measure: 'Mesurer',
      measuring: 'Mesure...',
      mapFocus: 'Focus carte',
      balancedView: 'Vue équilibrée',
      balancedViewDescription: 'Restaure la mise en page équilibrée où le convertisseur et la carte partagent l\'écran.',
      mapFocusDescription: 'Agrandit la carte pour occuper l\'essentiel de l\'écran et masquer les panneaux latéraux.',
      projectLayers: 'Couches du projet',
      showAll: 'Tout afficher',
      hideAll: 'Tout masquer',
      measureResults: 'Résultats de mesure',
      distance: 'Distance',
      angle: 'Angle',
      meters: 'mètres',
      kilometers: 'kilomètres',
      degree: 'degré (°)',
      measureHint: 'Cliquer sur les points convertis de la carte pour ajouter des points de mesure (3+ pour une aire)',
      measureEmpty: 'Activez Mesurer, puis cliquez sur deux points convertis de la carte.',
      convertedPoint: 'Point converti',
      clickSecondPoint: 'Cliquez sur un deuxième point converti pour P2',
    },
    converter: {
      quickActions: 'Actions rapides',
      goToBulk: 'Aller au lot',
      goToExports: 'Aller aux exports',
      resetBulk: 'Réinitialiser le lot',
      autoDetected: 'SCR détecté automatiquement',
      detectedTop: 'Nous avons détecté ces {{count}} systèmes de coordonnées les plus plausibles. Cliquez sur une option ci-dessous pour la choisir :',
      whyRankedFirst: 'Pourquoi {{code}} est classé en tête',
      whyNotSecond: 'Pourquoi pas le n°2 ?',
      selected: 'SÉLECTIONNÉ',
      match: '{{count}}% de correspondance',
      fromCrs: 'SCR source',
      toCrs: 'SCR cible',
      swapCrsTitle: 'Inverser SCR source / cible',
      swapCrsDescription: 'Inverse les systèmes de coordonnées source et cible. Pratique pour lancer rapidement la conversion inverse.',
      swapCrsAria: 'Inverser le SCR source et le SCR cible',
      undoAction: 'Annuler',
      redoAction: 'Rétablir',
      projectPresets: 'Préréglages projet',
      summary: {
        high: 'Confiance élevée',
        good: 'Bonne confiance',
        moderate: 'Confiance modérée',
        low: 'Faible confiance',
        primarySignal: 'Signal principal : {{reason}}',
        rankingStrength: 'Force du classement : {{label}} ({{percent}}%).',
        gapClear: 'Écart avec le candidat suivant : {{points}} points. Le choix est net.',
        gapReview: 'Écart avec le candidat suivant : {{points}} points. Le choix est cohérent mais mérite une vérification rapide.',
        gapManual: 'Écart avec le candidat suivant : {{points}} points. Les meilleurs candidats sont proches, une confirmation manuelle est recommandée.',
        geographicPenalty: 'Filtre métier appliqué : les SCR projetés ont été déclassés car l\'entrée ressemble à des coordonnées géographiques en degrés.',
        projectedPenalty: 'Filtre métier appliqué : les SCR géographiques ont été déclassés car l\'entrée ressemble à des coordonnées projetées en mètres.',
        comparison: '{{top}} est resté devant {{second}} avec un écart de {{points}} points. Signal du n°2 : {{reason}}',
      },
    },
    panels: {
      searchTitle: 'Recherche et filtre des points',
      searchPlaceholder: 'Rechercher par nom, ID...',
      crs: 'SCR',
      allCrs: 'Tous les SCR',
      sourceType: 'Type de source',
      allTypes: 'Tous les types',
      hideAdvanced: 'Masquer les options avancées',
      showAdvanced: 'Afficher les options avancées',
      elevationMin: 'Altitude min (m)',
      elevationMax: 'Altitude max (m)',
      min: 'Min',
      max: 'Max',
      matchingPoints: 'Correspondance : {{count}} / {{total}} points',
      applyFilter: 'Appliquer le filtre',
      clear: 'Effacer',
      multiMeasurementsTitle: 'Mesures multipoints',
      live: 'Temps réel',
      pointsShort: 'pts',
      distance: 'Distance',
      avgElevation: 'Alt. moy.',
      gain: 'Gain',
      loss: 'Perte',
      minElevation: 'Alt. min',
      maxElevation: 'Alt. max',
      area: 'Aire',
      perimeter: 'Périmètre',
      closePolygon: 'Fermer le polygone',
      exportProfile: 'Exporter le profil',
      measurementNamePlaceholder: 'Nommer cette mesure...',
      save: 'Enregistrer',
      saved: 'Enregistré',
      listView: 'Vue liste',
      compareTable: 'Tableau comparatif',
      exportSavedCsv: 'Exporter le CSV enregistré',
      enableMeasure: 'Activez le mode mesure et cliquez sur 2 points ou plus pour commencer',
      batchOperationsTitle: 'Opérations par lot',
      pointsSelectedFromTotal: '{{count}} points sélectionnés sur {{total}} au total',
      pointsTotal: '{{total}} points au total',
      operation: 'Opération',
      selectOperation: 'Sélectionner une opération',
      viewStatistics: 'Voir les statistiques',
      exportCsv: 'Exporter en CSV',
      addElevationOffset: 'Ajouter un décalage altimétrique',
      deleteSelected: 'Supprimer la sélection',
      elevationOffset: 'Décalage altimétrique (m)',
      elevationOffsetExample: 'ex. 2.5 ou -1.5',
      addOffsetToPoints: 'Ajout de {{offset}} m à l\'altitude des {{count}} points',
      deleteWarning: 'Cela supprimera définitivement {{count}} point(s). Cette action est irréversible.',
      confirmDelete: 'Confirmer la suppression',
      yesDelete: 'Oui, supprimer',
      cancel: 'Annuler',
      exportPoints: 'Exporter {{count}} points',
      applyOffset: 'Appliquer le décalage à {{count}} points',
      selectOperationAbove: 'Sélectionnez une opération ci-dessus',
      invalidElevationOffset: 'Décalage altimétrique invalide',
      batchStatsTitle: 'Statistiques par lot',
      elevations: 'Altitudes',
      avg: 'Moy.',
      crsDistribution: 'Répartition des SCR',
      sourceTypes: 'Types de source',
      diagnosticsTitle: 'Diagnostic de performance',
      healthLarge: 'VOLUMINEUX',
      healthModerate: 'MODÉRÉ',
      healthGood: 'BON',
      data: 'Données',
      performance: 'Performance',
      points: 'Points',
      lines: 'Lignes',
      polylines: 'Polylignes',
      arcs: 'Arcs',
      circles: 'Cercles',
      ellipses: 'Ellipses',
      splines: 'Splines',
      bulgeArcs: 'Arcs bulge',
      proxyCurves: 'Courbes proxy',
      approxCurves: 'Courbes approx.',
      vertices: 'Sommets',
      memory: 'Mémoire',
      render: 'Rendu',
      fps: 'FPS',
      optimizationTips: 'Conseils d\'optimisation',
      tipsLargePointCount: 'Grand nombre de points : activer le suppressseur de doublons ou filtrer les points',
      tipsManyVertices: 'Beaucoup de sommets : la géométrie CAO est complexe ; dézoomez pour un rendu plus rapide',
      tipsHighMemory: 'Utilisation mémoire élevée : envisagez de découper le fichier',
      tipsLowFps: 'FPS faible : essayez de désactiver les libellés ou de zoomer sur une zone précise',
      dxfLayersTitle: 'Couches DXF',
      noDxfLayerData: 'Aucune donnée de couche DXF disponible. Importez un DXF ou un DWG pour voir son arborescence de couches.',
      visibleFraction: '{{visible}} / {{total}} visibles',
      declared: 'Déclarées',
      standardized: 'Standardisées',
      renamed: 'Renommées',
      showAllLayers: 'Afficher toutes les couches',
      showAllLayersDescription: 'Rend toutes les couches DXF visibles simultanément sur la carte.',
      hideAllLayers: 'Masquer toutes les couches',
      hideAllLayersDescription: 'Masque toutes les couches DXF d\'un seul coup sur la carte.',
      showAll: 'Tout afficher',
      hideAll: 'Tout masquer',
      totalEntities: 'Entités totales',
      textEntities: 'Entités texte',
      toggleLayerTitle: 'Basculer la couche : {{name}}\nNoms d\'origine : {{originalNames}}',
      elevationProfileTitle: 'Profil altimétrique',
      addMeasurementPoints: 'Ajoutez 2 points de mesure ou plus pour générer le profil',
      coverage: 'Couverture',
      measuredPointHeights: 'Altitudes mesurées des points',
      onlineProfileUnavailable: 'Impossible de récupérer le profil altimétrique en ligne.',
      terrainProfile: 'Profil terrain IGN GéoPlateforme',
      fallbackHeights: 'Repli : altitudes des points sélectionnés uniquement',
      sampledElevations: '{{count}} altitudes échantillonnées',
      selectedPoints: '{{count}} points sélectionnés',
      loadingTerrain: 'Chargement des échantillons terrain...',
      elevation: 'Altitude',
      total: 'Total',
      samples: 'Échantillons',
      selected: 'Sélectionnés',
      terrainChange: 'Variation du terrain',
      slope: 'Pente',
    },
  },
};

const resolvePath = (object, path) => path.split('.').reduce((acc, key) => (acc && acc[key] !== undefined ? acc[key] : undefined), object);

export const createTranslator = (language = 'en') => {
  const activeLanguage = UI_COPY[language] ? language : 'en';
  return (path, replacements = {}) => {
    const template = resolvePath(UI_COPY[activeLanguage], path) ?? resolvePath(UI_COPY.en, path) ?? path;
    if (typeof template !== 'string') return template;
    return template.replace(/\{\{\s*(\w+)\s*\}\}/g, (_, key) => {
      const value = replacements[key];
      return value === undefined || value === null ? '' : String(value);
    });
  };
};